### ISSUE TITLE
Missing mdp file for first minimization in MD simulation (s1.sh)?

### ISSUE THREAD

**Issue by bkapili** [allison-group/structural-phylogenetics-bootstrap#1]
When preparing the .tpr file for the first energy minimization run, is the grompp input (i.e., `min_sd.mdp`) user-supplied? Or is it already included in the GMX directory? If it's already provided, I can't seem to find it.

Thank you for any guidance you can offer!

-- Bennett

Issue found on line:
https://github.com/allison-group/structural-phylogenetics-bootstrap/blob/742e943c113387fd71e8e81dffa52e569343103c/MD/GMX/s1.sh#L8

**Comment by janerallison** [comment]
So sorry it took me so long to respond to this! The min_sd.mdp file should have been provided - I just uploaded it now.

**Comment by bkapili** [comment]
Thank you!
