### ISSUE TITLE
Bootstrap workflow subtrees.py missing

### ISSUE THREAD

**Issue by Nuta0** [allison-group/structural-phylogenetics-bootstrap#2]
I would like to know where to find the subtrees.py script.

**Comment by proteinmechanic** [comment]
Hi @Nuta0, 

Sorry for not being clear on this earlier. 
I assume you are referring to sumtrees.py! The sumtrees.py is a python package you can get from Dendropy (https://dendropy.org/programs/sumtrees.html). 

At present we do not host external packages.

Apologies for the inconvenience. 

/A
